"""empty message

Revision ID: 68801a8c35eb
Revises: f2ce5bdbbc9d
Create Date: 2024-04-06 20:23:36.031073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68801a8c35eb'
down_revision = 'f2ce5bdbbc9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
